apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrower360
  labels:
    app: borrower360
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: borrower360
  template:
    metadata:
      labels:
        app: borrower360
    spec:
      containers:
        - name: borrower360
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: APP_MODULE
              value: {{ .Values.env.appModule | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel | quote }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: borrower360-secrets
                  key: API_KEY
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: 8000
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: 8000
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
